%% =========================================================================
%  Noise Sensitivity Heatmap (supplementary, not in the paper)
%
%  Displays the noise-sensitivity comparison figure from previously
%  recorded numbers. For a version that actually RUNS all three methods
%  across noise levels and computes these numbers fresh, see
%  noise_sensitivity_sweep.m in this same folder -- that script produces
%  the same style of figure via the same plot_metric_heatmap.m utility,
%  but from a live fit rather than these hardcoded values.
% =========================================================================
close all; clc;
thisDir = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(thisDir, 'utils')));
set(0,'DefaultFigureWindowStyle','docked');

%% -------------------- DATA -----------------------------------------------
noiseLabels  = {'0%','5%','10%','15%'};
methodLabels = {'SINDy','E-SINDy','RI-SINDy'};

correctTerms = [ ...
    7,   7,   7 ;
    NaN, 7,   7 ;
    NaN, 2,   6 ;
    NaN, 3,   6 ];

spuriousTerms = [ ...
    0, 0, 0 ;
    10,5,0 ;
    11,4,1 ;
    8,4,1 ];

relL2 = [ ...
    0.594,0.224,0.524 ;
    NaN,0.398,0.351 ;
    NaN,NaN,0.452 ;
    NaN,0.427,0.488 ];

correctMax = 7;

%% -------------------- FIGURE ---------------------------------------------
figure('Color','w',...
       'Position',[100 100 1250 380],... % Widen to comfortably fit colorbars
       'Name','Goodwin Noise Sensitivity');

subplot(1,3,1)
plot_metric_heatmap(correctTerms,...
    noiseLabels,...
    methodLabels,...
    'Correct Terms Recovered',...
    'blue_white',...
    correctMax,...
    [0, 7]); % Scale from 0 to 7

subplot(1,3,2)
plot_metric_heatmap(spuriousTerms,...
    noiseLabels,...
    methodLabels,...
    'Spurious Terms Identified',...
    'orange_white',...
    [],...
    []); % Automatic scale

subplot(1,3,3)
plot_metric_heatmap(relL2,...
    noiseLabels,...
    methodLabels,...
    'Relative L_2 Error',...
    'orange_white',...
    [],...
    [0, 0.6]); % Scale from 0 to 0.6 (where 0.6 is darkest orange)

sgtitle('Goodwin Oscillator: Noise Sensitivity',...
    'FontSize',11,...
    'FontWeight','normal');